CREATE DATABASE tienda;
USE tienda;

DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS PRODUCTS;

CREATE TABLE ROLES (
    RID INT AUTO_INCREMENT PRIMARY KEY,
    ROLE_NAME VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT check_role_name CHECK (ROLE_NAME IN ('ADMIN', 'VEN'))
);

CREATE TABLE USERS (
    UID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    USER_PASSWORD VARCHAR(60) NOT NULL,
    USER_NAME VARCHAR(50) NOT NULL,
    ROLE_ID INT NOT NULL,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(RID)
);

CREATE TABLE PRODUCTS (
  PID INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(255) NOT NULL,
  PRECIO DECIMAL(10,2) NOT NULL,
  IMAGEN_URL VARCHAR(500), -- URL final de la imagen (local o externa)
  IMAGEN_TIPO ENUM('upload', 'url') NOT NULL, -- Tipo de imagen
  IMAGEN_NOMBRE VARCHAR(255), -- Nombre original (solo para uploads)
  IMAGEN_MIME VARCHAR(50), -- Tipo MIME (image/jpeg, image/png, etc.)
  USER_ID INT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USERS(UID)
);


-- Insertar los roles primero
INSERT INTO ROLES (ROLE_NAME) VALUES ('ADMIN');
INSERT INTO ROLES (ROLE_NAME) VALUES ('VEN');

SELECT * FROM USERS;

-- ACTUALIZAR ROLE ADMIN
UPDATE USERS
SET ROLE_ID = 1
WHERE EMAIL = 'kevin@ejemplo.com';